App\Form\Model\PlyerDto:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 3
          max: 250
          minMessage: 'The name must be at least {{ limit }} characters long'
          maxMessage: 'The name cannot be longer than {{ limit }} characters'
    age:
      - NotBlank: ~
      - Range:
          min: 1
          max: 180
          notInRangeMessage: 'The age must be between {{ min }} years and {{ max }} years'