version: "3"

services:
  mysql:
    image: 'mysql'
    container_name: mysql
    environment:
      - MYSQL_DATABASE=ssl_db
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_ROOT_PASSWORD=my_password
    ports:
      - "3306:3306"